In [ ]:
"""goldbach_conjecture.ipynb"""

# Cell 01

#sum of two odd primes is equal to an even integer > 4

import numpy as np
from sympy import prime  #generates primes

test_limit = 100 #nth prime we go upto

# Use a list comprehension to create an array of the first 'n' ODD primes
primes = np.array([prime(n) for n in range(2, test_limit)]) # list comprehesion, read backwards inside out
# 2nd prime starting, upto 99th prime

print(primes[:10]) #slicing syntax [start=0: stop=len(): step=1]
print(primes[-10:]) #negative indexes are relative to the right (end), # no stop values, python assume length to the end size-1

[ 3  5  7 11 13 17 19 23 29 31]
[463 467 479 487 491 499 503 509 521 523]


In [ ]:
# Cell 02 - Generate all pairs of primes (with repetition)

from itertools import combinations_with_replacement

prime_pairs = [*combinations_with_replacement(primes, 2)]
#asterisk above with iterator will call this until it's complete
print(len(prime_pairs))

[*zip(prime_pairs[:5], prime_pairs[98:], prime_pairs[195:])]
#slicing syntax, three slices (lists) - given 0,4 in 1st slice (1st column), 2d list of rows and columns, places together two columns

4851


[((3, 3), (5, 5), (7, 7)),
 ((3, 5), (5, 7), (7, 11)),
 ((3, 7), (5, 11), (7, 13)),
 ((3, 11), (5, 13), (7, 17)),
 ((3, 13), (5, 17), (7, 19))]

In [ ]:
# Cell 03 - Create a sorted array containing the unique sums of each prime pairs

summed_pairs = np.sort(np.unique(np.array([sum(pair) for pair in prime_pairs])))
#read from inside out, sum prime pairs 1st, create array, need only one pair that adds to #, for every even int, then sort
print(summed_pairs[:10]) #1st 10
print(summed_pairs[-10:]) # last 10

[ 6  8 10 12 14 16 18 20 22 24]
[1018 1020 1022 1024 1026 1030 1032 1042 1044 1046]


In [4]:
# Cell 04

"""
Determine which EVEN integers from 6 to 900 (inclusive) are NOT in
the list of summed prime pairs. The numpy function setdiff1d() returns
any elements in the first array that are not also in the second array
"""

violations = np.setdiff1d(range(6, 902, 2), summed_pairs)

print(f"Number of Goldbach violations up to 900: {len(violations)}")
if len(violations > 0):
    print(violations)

Number of Goldbach violations up to 900: 0
