In [ ]:
#Cell 01

import numpy as np
from IPython.core.display import Math
from qis101_utils import as_latex
from scipy import linalg


# Hermitian (aka dagger) matrix inverrse is Hermitian
# Create a Hermitian matrix h and show is conjugate transpose is also Hermitian
#Consider the 4x4 base case which can be extended to other larger matrices

h = np.array([[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, -1, 0], [0, 1, 0, -1]])

h_inverse = np.linalg.inv(h)

h_conj_transpose = h.conj().T

print(h)

print("Is H Hermitian?", linalg.ishermitian(h))

print(h_inverse)

print("Is H inverse Hermitian?", linalg.ishermitian(h_inverse))

#Lets go further and show that if H is a Hermitian matrix with complex values, then H inverse is Hermitian.

#Reference Gemini AI for the below code modified by me:

def generate_random_hermitian_matrix(size, low_real=-5, high_real=5, low_imag=-5, high_imag=5):
    """
    Generates a random square Hermitian matrix of a given size with complex values.

    Args:
        size (int): The dimension of the square matrix (e.g., 4 for a 4x4 matrix).
        low_real (float): Lower bound for the real part of random numbers.
        high_real (float): Upper bound for the real part of random numbers.
        low_imag (float): Lower bound for the imaginary part of random numbers.
        high_imag (float): Upper bound for the imaginary part of random numbers.

    Returns:
        numpy.ndarray: A randomly generated Hermitian matrix.
    """
    if size <= 0:
        raise ValueError("Matrix size must be a positive integer.")

    # Create an empty matrix of the specified size and complex dtype
    hermitian_matrix = np.zeros((size, size), dtype=complex)

    # Fill the upper triangle and diagonal with random complex numbers
    # and then enforce the Hermitian property.
    for i in range(size):
        # Diagonal elements must be real
        hermitian_matrix[i, i] = np.random.uniform(low_real, high_real)

        # Fill upper triangle (j > i) with random complex numbers
        for j in range(i + 1, size):
            real_part = np.random.uniform(low_real, high_real)
            imag_part = np.random.uniform(low_imag, high_imag)
            hermitian_matrix[i, j] = complex(real_part, imag_part)
            # Enforce Hermitian property: a[j,i] = conjugate(a[i,j])
            hermitian_matrix[j, i] = np.conjugate(hermitian_matrix[i, j])

    return hermitian_matrix

# Generate a 4x4 random Hermitian matrix
random_hermitian_matrix = generate_random_hermitian_matrix(4)

print("Generated 4x4 Random Hermitian Matrix:")
print(random_hermitian_matrix)

# Verify if the matrix is Hermitian using scipy.linalg.ishermitian
is_hermitian_verified = linalg.ishermitian(random_hermitian_matrix)
print("\nIs the random matrix Hermitian?", is_hermitian_verified)

random_hermitian_matrix_inverse = np.linalg.inv(random_hermitian_matrix)

# Verify if the inverse matrix is Hermitian using scipy.linalg.ishermitian
is_hermitian_verified2 = linalg.ishermitian(random_hermitian_matrix_inverse)
print("\nIs the inverse of a random matrix also Hermitian?", is_hermitian_verified)




[[ 1  0  1  0]
 [ 0  1  0  1]
 [ 1  0 -1  0]
 [ 0  1  0 -1]]
Is H Hermitian? True
[[ 0.5  0.   0.5  0. ]
 [ 0.   0.5  0.   0.5]
 [ 0.5 -0.  -0.5 -0. ]
 [-0.   0.5 -0.  -0.5]]
Is H inverse Hermitian? True
Generated 4x4 Random Hermitian Matrix:
[[-3.85774895+0.j          3.41678418-3.14835178j  1.084756  -3.05606781j
  -2.98819907+4.35764362j]
 [ 3.41678418+3.14835178j -0.97565982+0.j          2.93582318+3.37517873j
  -1.89956311+1.33218504j]
 [ 1.084756  +3.05606781j  2.93582318-3.37517873j -2.13625614+0.j
  -0.45400584-2.92517276j]
 [-2.98819907-4.35764362j -1.89956311-1.33218504j -0.45400584+2.92517276j
  -0.89518761+0.j        ]]

Is the random matrix Hermitian? True

Is the inverse of a random matrix also Hermitian? True


In [26]:
#Cell 02

#Show that a Hermitian matrix raised to an integer exponent is also Hermitian

# Lets re-use the random Hermitian matrix generator code from the prior cell assume n is not 1 Check is H^n is Hermitian


#since H^-2=(H^2)^-1 we can invert the square Hermitian matrix and check if it's indeed Hermitian

h2 = np.matmul(random_hermitian_matrix,random_hermitian_matrix)
h3 = np.matmul(random_hermitian_matrix, random_hermitian_matrix,random_hermitian_matrix)
h4 = np.linalg.matrix_power(random_hermitian_matrix, 4)


h_inverse2 = np.linalg.inv(h2)
h_inverse3 = np.linalg.inv(h3)
h_inverse4 = np.linalg.inv(h4)

is_hermitian_verified5 = linalg.ishermitian(h_inverse2)
print("\nIs the H to the negative 2 power of a random matrix also Hermitian?", is_hermitian_verified)
is_hermitian_verified6 = linalg.ishermitian(h_inverse3)
print("\nIs the H to the negative 3 power of a random matrix also Hermitian?", is_hermitian_verified)
is_hermitian_verified7 = linalg.ishermitian(h_inverse4)
print("\nIs the H to the negative 4 power of a random matrix also Hermitian?", is_hermitian_verified)

print("WLOG, we have shown H^-1 is always Hermitian above")

print("WLOG, H^0 is I=identity matrix which is always Hermitian.")

# Verify if the inverse matrix is Hermitian using scipy.linalg.ishermitian
is_hermitian_verified2 = linalg.ishermitian(h2)
print("\nIs the square of a random matrix also Hermitian?", is_hermitian_verified)

# Verify if the inverse matrix is Hermitian using scipy.linalg.ishermitian
is_hermitian_verified3 = linalg.ishermitian(h3)
print("\nIs the cube of a random matrix also Hermitian?", is_hermitian_verified)

# Verify if the inverse matrix is Hermitian using scipy.linalg.ishermitian
is_hermitian_verified4 = linalg.ishermitian(h4)
print("\nIs the fourth power of a random matrix also Hermitian?", is_hermitian_verified)



Is the H to the negative 2 power of a random matrix also Hermitian? True

Is the H to the negative 3 power of a random matrix also Hermitian? True

Is the H to the negative 4 power of a random matrix also Hermitian? True
WLOG, we have shown H^-1 is always Hermitian above
WLOG, H^0 is I=identity matrix which is always Hermitian.

Is the square of a random matrix also Hermitian? True

Is the cube of a random matrix also Hermitian? True

Is the fourth power of a random matrix also Hermitian? True
